Story/cico 13
diging/citesphere-connector pull request #11
Opened 2024-11-21 19:18 UTC by jophals

2024-11-21 19:21 UTC, jophals commented
Created new PR to track all tickets related to CICO-6

2024-12-20 19:56 UTC, jdamerow requested changes

2024-12-20 19:56 UTC, jdamerow commented on .github/workflows/github-actions-demo.yml
I don't think this action is doing anything? Just checking out and installing ruff?

2024-12-20 19:56 UTC, jdamerow commented on README.md
> +
I think the pre-commit hooks need to be installed too, don't they?

2024-12-20 19:56 UTC, jdamerow commented on pyproject.toml
> +"Citesphere" = "https://diging-dev.asu.edu/citesphere-review/"
Let's take this out.

2024-12-20 19:56 UTC, jdamerow commented on requirements.txt
> +virtualenv==20.27.1
I don't think this needs to be installed?

2024-12-20 19:56 UTC, jdamerow commented on requirements.txt
> +virtualenv==20.27.1
And does it really need all these dependencies?

2024-12-20 19:56 UTC, jdamerow commented on setup.py
> +        "Citesphere": "https://diging-dev.asu.edu/citesphere-review/",
same here

2024-12-20 19:56 UTC, jdamerow commented on src/__pycache__/CitesphereConnector.cpython-310.pyc
pychache folder should not be pushed

2024-12-20 19:56 UTC, jdamerow commented on .github/workflows/github-actions-demo.yml
Also, the action should run the tests.

2025-01-03 01:48 UTC, jophals commented on README.md
> +
It was my understanding that as long as the pre-commit yaml file is present, you don't need to directly install anything

2025-02-27 21:39 UTC, jdamerow commented on README.md
> +
You need to install them locally I believe

2025-02-27 21:40 UTC, merged